# Generated by Django 3.2.14 on 2022-12-28 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('Rideid', models.AutoField(primary_key=True, serialize=False)),
                ('Ridemode', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=255)),
                ('Departure_Place', models.CharField(max_length=255)),
                ('Departure_time', models.DateTimeField()),
                ('Arrival_palce', models.CharField(max_length=255)),
                ('Allowed_Passengers', models.CharField(max_length=255)),
                ('Arrival_time', models.DateTimeField()),
                ('Price', models.CharField(max_length=255)),
                ('RiderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OngoingRides',
            fields=[
                ('Ongoingid', models.AutoField(primary_key=True, serialize=False)),
                ('RideStatus', models.CharField(choices=[('complated', 'complated'), ('ongoing', 'ongoing'), ('cancelled', 'cancelled')], max_length=255)),
                ('comments', models.CharField(max_length=1000)),
                ('Passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Rideid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride.rides')),
            ],
        ),
    ]
