# Generated by Django 3.2.14 on 2022-12-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='Ridestatus',
            field=models.CharField(choices=[('complated', 'complated'), ('pending', 'pending'), ('ongoing', 'ongoing'), ('cancelled', 'cancelled')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ongoingrides',
            name='RideStatus',
            field=models.CharField(choices=[('complated', 'complated'), ('pending', 'pending'), ('ongoing', 'ongoing'), ('cancelled', 'cancelled')], max_length=255),
        ),
    ]
