# Generated by Django 3.2.14 on 2023-03-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20221228_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingrides',
            name='RideStatus',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('ongoing', 'ongoing'), ('cancelled', 'cancelled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='rides',
            name='Ridemode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rides',
            name='Ridestatus',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('ongoing', 'ongoing'), ('cancelled', 'cancelled')], max_length=255),
        ),
    ]
