# Generated by Django 3.2.14 on 2023-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_auto_20230313_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='Phone_Number_Customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='Phone_Number_rider',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
