# Generated by Django 3.2.14 on 2023-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_auto_20230326_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingrides',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
