# Generated by Django 3.2.14 on 2022-12-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20221228_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='User',
            new_name='UserID',
        ),
    ]
