# Generated by Django 3.2.14 on 2023-03-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20230320_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='Contry',
        ),
    ]
